# Telling docker-compose to build the client and server images and run them in containers.

services:
  server:
    image: changrtanay/docksv4:server
    # Giving the container a name.
    container_name: server_c
    ports:
      - "8080:8080"
    networks:
      - mern_network
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules

  # Telling docker-compose to build the frontend image using the Dockerfile in the frontend directory.
  client:
    image: changrtanay/docksv4:client
    # Giving the container a name.
    container_name: client_c
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "3000:3000"  
    networks:
      - mern_network
    # Mapping the client directory on the host machine to the /app directory on the container.
    volumes:
      - ./client:/app
      - /app/node_modules
    # Allows you to run container in detached mode.
    stdin_open: true
    tty: true

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally


# cd server 
# docker build -t changrtanay/docksv4:server .
# cd ../client
# docker build -t changrtanay/docksv4:client .
# cd ..

# docker-compose up -d
# docker-compose ps
# docker-compose down

# docker login
# docker push changrtanay/docksv4:server
# docker push changrtanay/docksv4:client



# docker pull rakeshpotnuru/productivity-app-demo:client

# docker tag docksv4-client changrtanay/docksv4:client
# docker tag docksv4-server changrtanay/docksv4:server



# docker network create docksv4-network
# docker run --name mongodb_c -d -p 27017:27017 --network docksv4-network -v ~/opt/data:/data/db mongo:latest
# docker network connect docksv4-network mongodb_c (not required)

# docker run --name server_c -p 8080:8080 --network docksv4-network -d changrtanay/docksv4:server 
# nodemon -L index.js # Hot Reloading
# docker run --name server_c -p 8080:8080 --network docksv4-network -v D:\Files\html\docksv4\server:/app -v /app/node_modules changrtanay/docksv4:server

# docker run --name client_c -p 3000:3000 -d changrtanay/docksv4:client
# docker run --name client_c -p 3000:3000 -v D:\Files\html\docksv4\client:/app -v /app/node_modules changrtanay/docksv4:client # to reflect changes

# docker stop CONTAINER_NAME # stops the running container
# docker start CONTAINER_NAME # starts the container (Make sure a container is created first)



# docker-compose up -d
# docker-compose up --build
# docker-compose up -d -build
# docker-compose ps
# docker-compose logs -f client
# docker-compose logs -f server
# docker-compose exec server_c bash
# docker-compose exec client_c bash
# docker-compose exec mongodb bash
# docker-compose down